version: '3.8'
services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - store:/data
    networks:
      - rede1  

networks:
  rede1:
    external: true

volumes:
  store:
    driver: local     
